{% set name = "cheap_repr" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cheap_repr-{{ version }}.tar.gz
  sha256: 001a5cf8adb0305c7ad3152c5f776040ac2a559d97f85770cebcb28c6ca5a30f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - python >=3.6

test:
  imports:
    - cheap_repr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexmojaki/cheap_repr
  summary: Better version of repr/reprlib for short, cheap string representations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
